# Copyright 2014-2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

sudo: false
language: rust

env:
  - FLAGS=
  - FLAGS="--features glium-support"
script:
  - cargo build --verbose $(echo $FLAGS)
  - cargo test  --verbose $(echo $FLAGS)

cache:
  directories:
    - ~/.cargo
    - target

notifications:
  irc:
    nick: obj-rs
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
