[package]
name = "obj-rs"
version = "0.4.15"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
homepage = "https://github.com/simnalamburt/obj-rs"
repository = "https://github.com/simnalamburt/obj-rs"
documentation = "https://simnalamburt.github.io/obj-rs/"
license = "BSD-2-Clause"
keywords = ["graphics", "obj", "WaveFront", "3D", "parser"]
readme = "README.md"

description = """
Wavefront obj parser for Rust. It handles both 'obj' and 'mtl' formats.
"""

[lib]
name = "obj"

[features]
glium-support = ["glium"]

[dependencies]
glium = { version = "0.14.0", default-features = false, optional = true }
vec_map = "0.6.0"
rustc-serialize = "0.3"


[[example]]
name = "glium"

[dev_dependencies]
glium = "0.14.0"
